library(shinydashboard)
library(shiny)
library(dendextend)
library(shinyAce)
library(GGally)
library(colorspace)
library(scales)
library(grid)
library(devtools)
library(ggrepel)
library(shinythemes)
library(shinyjs)
library(markdown)
library(rmarkdown)
library(RColorBrewer)
library(svglite)
library(svgPanZoom)
library(purrr)
library(R.utils)
library(cairoDevice)
library(MASS)
library(gridExtra)
library(caret)
library(HDMD) 
library(cluster)
library(candisc)
library(svglite)
library(shiny)
library(scatterD3)
library(RColorBrewer)
library(colorspace)
library(rrcov)
library(rospca)
library(tidyverse)

# runApp("Desktop/R/D3CASS/app.R", display.mode = "showcase")
# options(shiny.error = browser)

getPalette <- colorRampPalette(brewer.pal(12, "Paired"))